// ColumnsEnum.hpp

enum {
	IMAGE_COLUMN,
	TITLE_COLUMN,
	NUM_COLS
};

// For iconView and results model
enum {
	ICON_IMAGE_COLUMN,
	ICON_TITLE_COLUMN,
	ICON_HREF,
	ICON_IMAGE_LINK,
	ICON_NUM_COLS
};

// For categories, actors model
enum {
	TREE_IMAGE_COLUMN,
	TREE_TITLE_COLUMN,
	TREE_HREF_COLUMN,
	TREE_NUM_COLS
};

// For playlists
enum {
	PLAYLIST_IMAGE_COLUMN,
	PLAYLIST_COMMENT_COLUMN,
	PLAYLIST_FILE_COLUMN,
	PLAYLIST_DOWNLOAD_COLUMN,
	PLAYLIST_NUM_COLS
};

// Play item dialog response
enum LinkResponse {
	LINK_RESPONSE_PLAY,
	LINK_RESPONSE_DOWNLOAD,
	LINK_RESPONSE_INFO,
	LINK_RESPONSE_CANCEL
};
